/**
 * Browns Color Range Palette Collection
 *
 * This module contains color palettes that combine brown tones with various color ranges.
 * Each palette uses browns heavily (60-70%) combined with a secondary color (30-40%).
 *
 * All palettes include both light and dark variants:
 * - Light variant: Uses darker colors suitable for light backgrounds
 * - Dark variant: Uses lighter colors suitable for dark backgrounds
 *
 * Available palettes:
 * - brownsAndReds: Browns combined with red tones
 * - brownsAndOranges: Browns combined with orange tones
 * - brownsAndYellows: Browns combined with yellow tones
 * - brownsAndGreens: Browns combined with green tones
 * - brownsAndBlues: Browns combined with blue tones
 * - brownsAndPurples: Browns combined with purple tones
 * - brownsAndGreys: Browns combined with grey tones
 * - brownsAndCharcoals: Browns combined with charcoal tones
 * - brownsAndCyans: Browns combined with cyan tones
 * - brownsAndMagentas: Browns combined with magenta tones
 * - brownsAndLightGrays: Browns combined with light gray tones
 */

export const brownsColorRangePalettes = {
  brownsAndReds: {
    light: {
      text: '#000000',
      null: '#4A3A2A',
      undefined: '#5A4A3A',
      boolean: '#6A2A2A',
      number: '#7A3A2A',
      bigint: '#7A4E2A',
      specialNumber: '#983020',
      string: '#5A3A2A',
      symbol: '#6A3A2A',
      function: '#8A4A3A',
      object: '#5A2A2A',
      array: '#7A4A3A',
      map: '#6A4A3A',
      set: '#7A3A3A',
      weakmap: '#8A5A4A',
      weakset: '#6A4A2A',
      date: '#9A5A4A',
      regexp: '#7A5A3A',
      error: '#8A3A2A',
      circularReference: '#4A3A2A',
      propertyKey: '#3A2A1A',
      punctuation: '#5A4A3A',
      indentGuide: '#ADA59D'
    },
    dark: {
      text: '#FFFFFF',
      null: '#D5C5B5',
      undefined: '#E5D5C5',
      boolean: '#F5A5A5',
      number: '#FFBBAA',
      bigint: '#FFCFAA',
      specialNumber: '#FFB1A0',
      string: '#E5C5B5',
      symbol: '#F5B5AA',
      function: '#FFDDC5',
      object: '#F5AAAA',
      array: '#FFD5C5',
      map: '#F5D5C5',
      set: '#FFCCBB',
      weakmap: '#FFE5D5',
      weakset: '#F5D5C5',
      date: '#FFEEDD',
      regexp: '#FFE5D5',
      error: '#FFBBAA',
      circularReference: '#D5C5B5',
      propertyKey: '#F5E5D5',
      punctuation: '#E5D5C5',
      indentGuide: '#736B63'
    }
  },
  brownsAndOranges: {
    light: {
      text: '#000000',
      null: '#4A3A2A',
      undefined: '#5A4A3A',
      boolean: '#7A4A2A',
      number: '#8A5A2A',
      bigint: '#8A6E2A',
      specialNumber: '#A85020',
      string: '#5A3A2A',
      symbol: '#6A4A2A',
      function: '#9A6A3A',
      object: '#6A3A2A',
      array: '#8A5A3A',
      map: '#7A5A3A',
      set: '#8A6A3A',
      weakmap: '#AA7A4A',
      weakset: '#7A5A3A',
      date: '#BB8A5A',
      regexp: '#8A6A4A',
      error: '#9A5A2A',
      circularReference: '#4A3A2A',
      propertyKey: '#3A2A1A',
      punctuation: '#5A4A3A',
      indentGuide: '#ADA59D'
    },
    dark: {
      text: '#FFFFFF',
      null: '#D5C5B5',
      undefined: '#E5D5C5',
      boolean: '#FFCC99',
      number: '#FFD5AA',
      bigint: '#FFE9AA',
      specialNumber: '#FFCBA0',
      string: '#E5C5B5',
      symbol: '#F5CCAA',
      function: '#FFDDBB',
      object: '#F5C5AA',
      array: '#FFD5BB',
      map: '#FFD5B5',
      set: '#FFDDBB',
      weakmap: '#FFEEDD',
      weakset: '#FFD5BB',
      date: '#FFF5DD',
      regexp: '#FFEECC',
      error: '#FFD5AA',
      circularReference: '#D5C5B5',
      propertyKey: '#F5E5D5',
      punctuation: '#E5D5C5',
      indentGuide: '#736B63'
    }
  },
  brownsAndYellows: {
    light: {
      text: '#000000',
      null: '#4A4A2A',
      undefined: '#5A5A3A',
      boolean: '#7A6A2A',
      number: '#8A7A2A',
      bigint: '#8A8E2A',
      specialNumber: '#A87020',
      string: '#5A4A2A',
      symbol: '#6A5A2A',
      function: '#9A8A3A',
      object: '#6A5A2A',
      array: '#8A7A3A',
      map: '#7A6A3A',
      set: '#8A8A3A',
      weakmap: '#AA9A4A',
      weakset: '#7A6A3A',
      date: '#BB9A5A',
      regexp: '#8A7A4A',
      error: '#9A7A2A',
      circularReference: '#4A4A2A',
      propertyKey: '#3A3A1A',
      punctuation: '#5A5A3A',
      indentGuide: '#ADAD9D'
    },
    dark: {
      text: '#FFFFFF',
      null: '#D5D5B5',
      undefined: '#E5E5C5',
      boolean: '#FFEEAA',
      number: '#FFEE99',
      bigint: '#FFFF99',
      specialNumber: '#FFE48F',
      string: '#E5D5B5',
      symbol: '#F5EEAA',
      function: '#FFFFBB',
      object: '#F5E5AA',
      array: '#FFFFCC',
      map: '#FFF5BB',
      set: '#FFFFDD',
      weakmap: '#FFFEDD',
      weakset: '#FFF5CC',
      date: '#FFFFEE',
      regexp: '#FFFDD5',
      error: '#FFEEAA',
      circularReference: '#D5D5B5',
      propertyKey: '#F5F5D5',
      punctuation: '#E5E5C5',
      indentGuide: '#737363'
    }
  },
  brownsAndGreens: {
    light: {
      text: '#000000',
      null: '#3A4A2A',
      undefined: '#4A5A3A',
      boolean: '#3A5A2A',
      number: '#5A6A3A',
      bigint: '#5A7E3A',
      specialNumber: '#508830',
      string: '#2A5A2A',
      symbol: '#4A5A2A',
      function: '#6A7A4A',
      object: '#4A5A2A',
      array: '#5A6A3A',
      map: '#4A6A3A',
      set: '#3A7A3A',
      weakmap: '#7A8A5A',
      weakset: '#5A6A3A',
      date: '#8A9A6A',
      regexp: '#6A7A4A',
      error: '#5A6A2A',
      circularReference: '#3A4A2A',
      propertyKey: '#2A3A1A',
      punctuation: '#4A5A3A',
      indentGuide: '#A5AD9D'
    },
    dark: {
      text: '#FFFFFF',
      null: '#C5D5B5',
      undefined: '#D5E5C5',
      boolean: '#B5E5A5',
      number: '#D5F5C5',
      bigint: '#D5FFC5',
      specialNumber: '#CBFFBB',
      string: '#A5E5A5',
      symbol: '#C5E5B5',
      function: '#E5FFD5',
      object: '#C5E5B5',
      array: '#D5F5C5',
      map: '#C5F5C5',
      set: '#B5FFBB',
      weakmap: '#EFFFDD',
      weakset: '#D5F5C5',
      date: '#F5FFEE',
      regexp: '#E5FFD5',
      error: '#D5F5B5',
      circularReference: '#C5D5B5',
      propertyKey: '#E5F5D5',
      punctuation: '#D5E5C5',
      indentGuide: '#6B7363'
    }
  },
  brownsAndBlues: {
    light: {
      text: '#000000',
      null: '#3A3A4A',
      undefined: '#4A4A5A',
      boolean: '#2A4A5A',
      number: '#4A5A6A',
      bigint: '#4A6E6A',
      specialNumber: '#405088',
      string: '#3A4A5A',
      symbol: '#3A5A6A',
      function: '#5A6A7A',
      object: '#4A4A5A',
      array: '#3A5A6A',
      map: '#4A5A7A',
      set: '#2A6A7A',
      weakmap: '#6A7A8A',
      weakset: '#4A5A6A',
      date: '#7A8A9A',
      regexp: '#5A6A7A',
      error: '#4A5A6A',
      circularReference: '#3A3A4A',
      propertyKey: '#2A2A3A',
      punctuation: '#4A4A5A',
      indentGuide: '#A5A5AD'
    },
    dark: {
      text: '#FFFFFF',
      null: '#C5C5D5',
      undefined: '#D5D5E5',
      boolean: '#A5CCDD',
      number: '#C5DDEE',
      bigint: '#C5F1EE',
      specialNumber: '#BBD3FF',
      string: '#B5D5E5',
      symbol: '#B5DDEE',
      function: '#D5EEFF',
      object: '#C5D5E5',
      array: '#B5DDEE',
      map: '#C5DDFF',
      set: '#A5EEFF',
      weakmap: '#EEFFFF',
      weakset: '#C5DDEE',
      date: '#F5FFFF',
      regexp: '#D5EEFF',
      error: '#C5DDEE',
      circularReference: '#C5C5D5',
      propertyKey: '#E5E5F5',
      punctuation: '#D5D5E5',
      indentGuide: '#6B6B73'
    }
  },
  brownsAndPurples: {
    light: {
      text: '#000000',
      null: '#4A3A4A',
      undefined: '#5A4A5A',
      boolean: '#5A2A5A',
      number: '#6A4A6A',
      bigint: '#6A5E6A',
      specialNumber: '#884088',
      string: '#4A3A5A',
      symbol: '#6A3A6A',
      function: '#7A5A7A',
      object: '#5A3A5A',
      array: '#6A4A7A',
      map: '#5A4A6A',
      set: '#7A4A7A',
      weakmap: '#8A6A8A',
      weakset: '#6A4A6A',
      date: '#9A7A9A',
      regexp: '#7A5A7A',
      error: '#7A4A6A',
      circularReference: '#4A3A4A',
      propertyKey: '#3A2A3A',
      punctuation: '#5A4A5A',
      indentGuide: '#ADA5AD'
    },
    dark: {
      text: '#FFFFFF',
      null: '#D5C5D5',
      undefined: '#E5D5E5',
      boolean: '#EEAAEE',
      number: '#F5CCF5',
      bigint: '#F5E0F5',
      specialNumber: '#FFC2FF',
      string: '#E5C5E5',
      symbol: '#F5BBF5',
      function: '#FFDDFF',
      object: '#EEB5EE',
      array: '#F5CCFF',
      map: '#EEC5EE',
      set: '#FFBBFF',
      weakmap: '#FFEEFF',
      weakset: '#F5CCF5',
      date: '#FFDDFF',
      regexp: '#FFDDFF',
      error: '#FFCCEE',
      circularReference: '#D5C5D5',
      propertyKey: '#F5E5F5',
      punctuation: '#E5D5E5',
      indentGuide: '#736B73'
    }
  },
  brownsAndGreys: {
    light: {
      text: '#000000',
      null: '#4A4A4A',
      undefined: '#5A5A5A',
      boolean: '#3A4A4A',
      number: '#5A5A5A',
      bigint: '#5A6E5A',
      specialNumber: '#787878',
      string: '#4A4A4A',
      symbol: '#4A5A5A',
      function: '#6A6A6A',
      object: '#4A4A4A',
      array: '#5A5A5A',
      map: '#5A6A6A',
      set: '#4A6A6A',
      weakmap: '#7A7A7A',
      weakset: '#5A5A5A',
      date: '#8A8A8A',
      regexp: '#6A6A6A',
      error: '#5A5A5A',
      circularReference: '#4A4A4A',
      propertyKey: '#3A3A3A',
      punctuation: '#5A5A5A',
      indentGuide: '#ADADAD'
    },
    dark: {
      text: '#FFFFFF',
      null: '#D5D5D5',
      undefined: '#E5E5E5',
      boolean: '#C5D5D5',
      number: '#E5E5E5',
      bigint: '#E5F9E5',
      specialNumber: '#FFFFFF',
      string: '#D5D5D5',
      symbol: '#D5E5E5',
      function: '#F5F5F5',
      object: '#D5D5D5',
      array: '#E5E5E5',
      map: '#E5F5F5',
      set: '#D5F5F5',
      weakmap: '#FFFFFF',
      weakset: '#E5E5E5',
      date: '#FFFFFF',
      regexp: '#F5F5F5',
      error: '#E5E5E5',
      circularReference: '#D5D5D5',
      propertyKey: '#F5F5F5',
      punctuation: '#E5E5E5',
      indentGuide: '#737373'
    }
  },
  brownsAndCharcoals: {
    light: {
      text: '#000000',
      null: '#3A3A3A',
      undefined: '#4A4A4A',
      boolean: '#2A3A3A',
      number: '#4A4A4A',
      bigint: '#4A5E4A',
      specialNumber: '#686868',
      string: '#3A3A3A',
      symbol: '#3A4A4A',
      function: '#5A5A5A',
      object: '#3A3A3A',
      array: '#4A4A4A',
      map: '#4A5A5A',
      set: '#3A5A5A',
      weakmap: '#6A6A6A',
      weakset: '#4A4A4A',
      date: '#7A7A7A',
      regexp: '#5A5A5A',
      error: '#4A4A4A',
      circularReference: '#3A3A3A',
      propertyKey: '#2A2A2A',
      punctuation: '#4A4A4A',
      indentGuide: '#A5A5A5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#C5C5C5',
      undefined: '#D5D5D5',
      boolean: '#B5C5C5',
      number: '#D5D5D5',
      bigint: '#D5E9D5',
      specialNumber: '#F3F3F3',
      string: '#C5C5C5',
      symbol: '#C5D5D5',
      function: '#E5E5E5',
      object: '#C5C5C5',
      array: '#D5D5D5',
      map: '#D5E5E5',
      set: '#C5E5E5',
      weakmap: '#F5F5F5',
      weakset: '#D5D5D5',
      date: '#FFFFFF',
      regexp: '#E5E5E5',
      error: '#D5D5D5',
      circularReference: '#C5C5C5',
      propertyKey: '#E5E5E5',
      punctuation: '#D5D5D5',
      indentGuide: '#6B6B6B'
    }
  },
  brownsAndCyans: {
    light: {
      text: '#000000',
      null: '#3A4A4A',
      undefined: '#4A5A5A',
      boolean: '#2A5A5A',
      number: '#4A6A6A',
      bigint: '#4A7E6A',
      specialNumber: '#408888',
      string: '#3A5A5A',
      symbol: '#3A6A6A',
      function: '#5A7A7A',
      object: '#4A5A5A',
      array: '#3A6A6A',
      map: '#4A6A7A',
      set: '#2A7A7A',
      weakmap: '#6A8A8A',
      weakset: '#4A6A6A',
      date: '#7A9A9A',
      regexp: '#5A7A7A',
      error: '#4A6A6A',
      circularReference: '#3A4A4A',
      propertyKey: '#2A3A3A',
      punctuation: '#4A5A5A',
      indentGuide: '#A5ADAD'
    },
    dark: {
      text: '#FFFFFF',
      null: '#C5D5D5',
      undefined: '#D5E5E5',
      boolean: '#A5EEDD',
      number: '#C5F5EE',
      bigint: '#C5FFEE',
      specialNumber: '#BBFFE4',
      string: '#B5E5DD',
      symbol: '#B5F5EE',
      function: '#D5FFEE',
      object: '#C5E5DD',
      array: '#B5F5EE',
      map: '#C5F5FF',
      set: '#A5FFEE',
      weakmap: '#EFFFFF',
      weakset: '#C5F5EE',
      date: '#F5FFFF',
      regexp: '#D5FFEE',
      error: '#C5F5EE',
      circularReference: '#C5D5D5',
      propertyKey: '#E5F5F5',
      punctuation: '#D5E5E5',
      indentGuide: '#6B7373'
    }
  },
  brownsAndMagentas: {
    light: {
      text: '#000000',
      null: '#4A3A4A',
      undefined: '#5A4A5A',
      boolean: '#6A2A5A',
      number: '#7A4A6A',
      bigint: '#7A5E6A',
      specialNumber: '#984060',
      string: '#5A3A5A',
      symbol: '#7A3A6A',
      function: '#8A5A7A',
      object: '#6A3A5A',
      array: '#7A4A6A',
      map: '#6A4A7A',
      set: '#8A3A7A',
      weakmap: '#9A6A8A',
      weakset: '#7A4A6A',
      date: '#AA7A9A',
      regexp: '#8A5A7A',
      error: '#8A4A6A',
      circularReference: '#4A3A4A',
      propertyKey: '#3A2A3A',
      punctuation: '#5A4A5A',
      indentGuide: '#ADA5AD'
    },
    dark: {
      text: '#FFFFFF',
      null: '#D5C5D5',
      undefined: '#E5D5E5',
      boolean: '#FFAADD',
      number: '#FFCCEE',
      bigint: '#FFE0EE',
      specialNumber: '#FFC2E4',
      string: '#E5C5DD',
      symbol: '#FFBBEE',
      function: '#FFDDEE',
      object: '#F5BBDD',
      array: '#FFCCEE',
      map: '#F5CCFF',
      set: '#FFAAFF',
      weakmap: '#FFEEFF',
      weakset: '#FFCCEE',
      date: '#FFDDF5',
      regexp: '#FFDDEE',
      error: '#FFCCDD',
      circularReference: '#D5C5D5',
      propertyKey: '#F5E5F5',
      punctuation: '#E5D5E5',
      indentGuide: '#736B73'
    }
  },
  brownsAndLightGrays: {
    light: {
      text: '#000000',
      null: '#5A5A5A',
      undefined: '#6A6A6A',
      boolean: '#4A5A5A',
      number: '#6A6A6A',
      bigint: '#6A7E6A',
      specialNumber: '#888888',
      string: '#5A5A5A',
      symbol: '#5A6A6A',
      function: '#7A7A7A',
      object: '#5A5A5A',
      array: '#6A6A6A',
      map: '#6A7A7A',
      set: '#5A7A7A',
      weakmap: '#8A8A8A',
      weakset: '#6A6A6A',
      date: '#9A9A9A',
      regexp: '#7A7A7A',
      error: '#6A6A6A',
      circularReference: '#5A5A5A',
      propertyKey: '#4A4A4A',
      punctuation: '#6A6A6A',
      indentGuide: '#B5B5B5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#E5E5E5',
      undefined: '#F5F5F5',
      boolean: '#D5E5E5',
      number: '#F5F5F5',
      bigint: '#F5FFF5',
      specialNumber: '#FFFFFF',
      string: '#E5E5E5',
      symbol: '#E5F5F5',
      function: '#FFFFFF',
      object: '#E5E5E5',
      array: '#F5F5F5',
      map: '#F5FFFF',
      set: '#E5FFFF',
      weakmap: '#FFFFFF',
      weakset: '#F5F5F5',
      date: '#FFFFFF',
      regexp: '#FFFFFF',
      error: '#F5F5F5',
      circularReference: '#E5E5E5',
      propertyKey: '#FFFFFF',
      punctuation: '#F5F5F5',
      indentGuide: '#7B7B7B'
    }
  }
} as const;
