/**
 * Charcoals Color Range Palettes Collection
 *
 * This file contains a collection of color palettes that combine charcoal tones (grays and dark neutrals)
 * with various color ranges. Each palette emphasizes charcoals (60-70%) over the secondary color (30-40%),
 * creating sophisticated, muted color schemes suitable for syntax highlighting.
 *
 * Each palette includes both light and dark variants:
 * - Light variant: Uses darker colors for visibility on light backgrounds
 * - Dark variant: Uses lighter colors for visibility on dark backgrounds
 */

import type { ColorPalette } from '../index.js';

export const charcoalsColorRangePalettes = {
  charcoalsAndReds: {
    light: {
      text: '#000000',
      null: '#3A3A3A',
      undefined: '#4A4A4A',
      boolean: '#5A5A5A',
      number: '#884444',
      bigint: '#885844',
      specialNumber: '#A63A3A',
      string: '#555555',
      symbol: '#775555',
      function: '#994444',
      object: '#2A2A2A',
      array: '#656565',
      map: '#665555',
      set: '#666666',
      weakmap: '#AA5555',
      weakset: '#444444',
      date: '#885555',
      regexp: '#505050',
      error: '#AA4444',
      circularReference: '#3A3A3A',
      propertyKey: '#2A2A2A',
      punctuation: '#4A4A4A',
      indentGuide: '#A5A5A5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#C5C5C5',
      undefined: '#D5D5D5',
      boolean: '#E5E5E5',
      number: '#FFAAAA',
      bigint: '#FFBEAA',
      specialNumber: '#FFA0A0',
      string: '#CACACA',
      symbol: '#FFBBBB',
      function: '#FF9999',
      object: '#B5B5B5',
      array: '#DFDFDF',
      map: '#FFCCCC',
      set: '#E0E0E0',
      weakmap: '#FFDDDD',
      weakset: '#CCCCCC',
      date: '#FFBBBB',
      regexp: '#D0D0D0',
      error: '#FF8888',
      circularReference: '#C5C5C5',
      propertyKey: '#EEEEEE',
      punctuation: '#D5D5D5',
      indentGuide: '#6B6B6B'
    }
  } as const satisfies { light: ColorPalette; dark: ColorPalette },

  charcoalsAndOranges: {
    light: {
      text: '#000000',
      null: '#3A3A3A',
      undefined: '#4A4A4A',
      boolean: '#5A5A5A',
      number: '#AA6644',
      bigint: '#AA7A44',
      specialNumber: '#C85C3A',
      string: '#555555',
      symbol: '#996655',
      function: '#BB7744',
      object: '#2A2A2A',
      array: '#656565',
      map: '#886644',
      set: '#666666',
      weakmap: '#CC7755',
      weakset: '#444444',
      date: '#AA7755',
      regexp: '#505050',
      error: '#BB6633',
      circularReference: '#3A3A3A',
      propertyKey: '#2A2A2A',
      punctuation: '#4A4A4A',
      indentGuide: '#A5A5A5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#C5C5C5',
      undefined: '#D5D5D5',
      boolean: '#E5E5E5',
      number: '#FFCC99',
      bigint: '#FFE099',
      specialNumber: '#FFC28F',
      string: '#CACACA',
      symbol: '#FFDDAA',
      function: '#FFBB88',
      object: '#B5B5B5',
      array: '#DFDFDF',
      map: '#FFDDBB',
      set: '#E0E0E0',
      weakmap: '#FFEEDD',
      weakset: '#CCCCCC',
      date: '#FFDDBB',
      regexp: '#D0D0D0',
      error: '#FFAA77',
      circularReference: '#C5C5C5',
      propertyKey: '#EEEEEE',
      punctuation: '#D5D5D5',
      indentGuide: '#6B6B6B'
    }
  } as const satisfies { light: ColorPalette; dark: ColorPalette },

  charcoalsAndYellows: {
    light: {
      text: '#000000',
      null: '#3A3A3A',
      undefined: '#4A4A4A',
      boolean: '#5A5A5A',
      number: '#998844',
      bigint: '#999C44',
      specialNumber: '#B77E3A',
      string: '#555555',
      symbol: '#887744',
      function: '#AA9944',
      object: '#2A2A2A',
      array: '#656565',
      map: '#998855',
      set: '#666666',
      weakmap: '#BBAA55',
      weakset: '#444444',
      date: '#AA9955',
      regexp: '#505050',
      error: '#AA9944',
      circularReference: '#3A3A3A',
      propertyKey: '#2A2A2A',
      punctuation: '#4A4A4A',
      indentGuide: '#A5A5A5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#C5C5C5',
      undefined: '#D5D5D5',
      boolean: '#E5E5E5',
      number: '#FFEE99',
      bigint: '#FFFF99',
      specialNumber: '#FFE48F',
      string: '#CACACA',
      symbol: '#FFFFAA',
      function: '#FFDD88',
      object: '#B5B5B5',
      array: '#DFDFDF',
      map: '#FFFFBB',
      set: '#E0E0E0',
      weakmap: '#FFFFCC',
      weakset: '#CCCCCC',
      date: '#FFFFBB',
      regexp: '#D0D0D0',
      error: '#FFDD77',
      circularReference: '#C5C5C5',
      propertyKey: '#EEEEEE',
      punctuation: '#D5D5D5',
      indentGuide: '#6B6B6B'
    }
  } as const satisfies { light: ColorPalette; dark: ColorPalette },

  charcoalsAndGreens: {
    light: {
      text: '#000000',
      null: '#3A3A3A',
      undefined: '#4A4A4A',
      boolean: '#5A5A5A',
      number: '#557744',
      bigint: '#558B44',
      specialNumber: '#4B953A',
      string: '#555555',
      symbol: '#668855',
      function: '#558844',
      object: '#2A2A2A',
      array: '#656565',
      map: '#669955',
      set: '#666666',
      weakmap: '#77AA55',
      weakset: '#444444',
      date: '#669955',
      regexp: '#505050',
      error: '#669944',
      circularReference: '#3A3A3A',
      propertyKey: '#2A2A2A',
      punctuation: '#4A4A4A',
      indentGuide: '#A5A5A5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#C5C5C5',
      undefined: '#D5D5D5',
      boolean: '#E5E5E5',
      number: '#AAFFAA',
      bigint: '#AAFFAA',
      specialNumber: '#A0FFA0',
      string: '#CACACA',
      symbol: '#BBFFBB',
      function: '#99FF99',
      object: '#B5B5B5',
      array: '#DFDFDF',
      map: '#CCFFCC',
      set: '#E0E0E0',
      weakmap: '#DDFFDD',
      weakset: '#CCCCCC',
      date: '#CCFFBB',
      regexp: '#D0D0D0',
      error: '#BBFF99',
      circularReference: '#C5C5C5',
      propertyKey: '#EEEEEE',
      punctuation: '#D5D5D5',
      indentGuide: '#6B6B6B'
    }
  } as const satisfies { light: ColorPalette; dark: ColorPalette },

  charcoalsAndBlues: {
    light: {
      text: '#000000',
      null: '#3A3A3A',
      undefined: '#4A4A4A',
      boolean: '#5A5A5A',
      number: '#446688',
      bigint: '#447A88',
      specialNumber: '#3A5CA6',
      string: '#555555',
      symbol: '#557799',
      function: '#5588AA',
      object: '#2A2A2A',
      array: '#656565',
      map: '#5599BB',
      set: '#666666',
      weakmap: '#66AACC',
      weakset: '#444444',
      date: '#5599AA',
      regexp: '#505050',
      error: '#4477AA',
      circularReference: '#3A3A3A',
      propertyKey: '#2A2A2A',
      punctuation: '#4A4A4A',
      indentGuide: '#A5A5A5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#C5C5C5',
      undefined: '#D5D5D5',
      boolean: '#E5E5E5',
      number: '#99CCFF',
      bigint: '#99E0FF',
      specialNumber: '#8FC2FF',
      string: '#CACACA',
      symbol: '#AADDFF',
      function: '#88BBFF',
      object: '#B5B5B5',
      array: '#DFDFDF',
      map: '#BBEEFF',
      set: '#E0E0E0',
      weakmap: '#CCFFFF',
      weakset: '#CCCCCC',
      date: '#BBDDFF',
      regexp: '#D0D0D0',
      error: '#88AAFF',
      circularReference: '#C5C5C5',
      propertyKey: '#EEEEEE',
      punctuation: '#D5D5D5',
      indentGuide: '#6B6B6B'
    }
  } as const satisfies { light: ColorPalette; dark: ColorPalette },

  charcoalsAndPurples: {
    light: {
      text: '#000000',
      null: '#3A3A3A',
      undefined: '#4A4A4A',
      boolean: '#5A5A5A',
      number: '#775588',
      bigint: '#776988',
      specialNumber: '#6D4BA6',
      string: '#555555',
      symbol: '#886699',
      function: '#9966AA',
      object: '#2A2A2A',
      array: '#656565',
      map: '#8877AA',
      set: '#666666',
      weakmap: '#AA77BB',
      weakset: '#444444',
      date: '#9977AA',
      regexp: '#505050',
      error: '#9955AA',
      circularReference: '#3A3A3A',
      propertyKey: '#2A2A2A',
      punctuation: '#4A4A4A',
      indentGuide: '#A5A5A5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#C5C5C5',
      undefined: '#D5D5D5',
      boolean: '#E5E5E5',
      number: '#DDAAFF',
      bigint: '#DDBEFF',
      specialNumber: '#D3A0FF',
      string: '#CACACA',
      symbol: '#EECCFF',
      function: '#CC99FF',
      object: '#B5B5B5',
      array: '#DFDFDF',
      map: '#EEDDFF',
      set: '#E0E0E0',
      weakmap: '#FFEEFF',
      weakset: '#CCCCCC',
      date: '#DDBBFF',
      regexp: '#D0D0D0',
      error: '#CC88FF',
      circularReference: '#C5C5C5',
      propertyKey: '#EEEEEE',
      punctuation: '#D5D5D5',
      indentGuide: '#6B6B6B'
    }
  } as const satisfies { light: ColorPalette; dark: ColorPalette },

  charcoalsAndBrowns: {
    light: {
      text: '#000000',
      null: '#3A3A3A',
      undefined: '#4A4A4A',
      boolean: '#5A5A5A',
      number: '#775533',
      bigint: '#776933',
      specialNumber: '#954B29',
      string: '#555555',
      symbol: '#886644',
      function: '#996655',
      object: '#2A2A2A',
      array: '#656565',
      map: '#887755',
      set: '#666666',
      weakmap: '#AA8866',
      weakset: '#444444',
      date: '#998866',
      regexp: '#505050',
      error: '#AA7744',
      circularReference: '#3A3A3A',
      propertyKey: '#2A2A2A',
      punctuation: '#4A4A4A',
      indentGuide: '#A5A5A5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#C5C5C5',
      undefined: '#D5D5D5',
      boolean: '#E5E5E5',
      number: '#DDBB99',
      bigint: '#DDCF99',
      specialNumber: '#FBB18F',
      string: '#CACACA',
      symbol: '#EECCAA',
      function: '#FFDDBB',
      object: '#B5B5B5',
      array: '#DFDFDF',
      map: '#EEDDBB',
      set: '#E0E0E0',
      weakmap: '#FFEEDD',
      weakset: '#CCCCCC',
      date: '#FFDDCC',
      regexp: '#D0D0D0',
      error: '#FFCCAA',
      circularReference: '#C5C5C5',
      propertyKey: '#EEEEEE',
      punctuation: '#D5D5D5',
      indentGuide: '#6B6B6B'
    }
  } as const satisfies { light: ColorPalette; dark: ColorPalette },

  charcoalsAndGreys: {
    light: {
      text: '#000000',
      null: '#2A2A2A',
      undefined: '#3A3A3A',
      boolean: '#4A4A4A',
      number: '#5A5A5A',
      bigint: '#5A6E5A',
      specialNumber: '#787878',
      string: '#333333',
      symbol: '#4D4D4D',
      function: '#666666',
      object: '#1A1A1A',
      array: '#555555',
      map: '#606060',
      set: '#575757',
      weakmap: '#6A6A6A',
      weakset: '#404040',
      date: '#626262',
      regexp: '#484848',
      error: '#676767',
      circularReference: '#2A2A2A',
      propertyKey: '#1A1A1A',
      punctuation: '#3A3A3A',
      indentGuide: '#9D9D9D'
    },
    dark: {
      text: '#FFFFFF',
      null: '#B5B5B5',
      undefined: '#C5C5C5',
      boolean: '#D5D5D5',
      number: '#E5E5E5',
      bigint: '#E5F9E5',
      specialNumber: '#FFFFFF',
      string: '#BABABA',
      symbol: '#CFCFCF',
      function: '#F0F0F0',
      object: '#A5A5A5',
      array: '#CCCCCC',
      map: '#DADADA',
      set: '#D8D8D8',
      weakmap: '#F5F5F5',
      weakset: '#C0C0C0',
      date: '#E0E0E0',
      regexp: '#CDCDCD',
      error: '#EFEFEF',
      circularReference: '#B5B5B5',
      propertyKey: '#DDDDDD',
      punctuation: '#C5C5C5',
      indentGuide: '#636363'
    }
  } as const satisfies { light: ColorPalette; dark: ColorPalette },

  charcoalsAndCyans: {
    light: {
      text: '#000000',
      null: '#3A3A3A',
      undefined: '#4A4A4A',
      boolean: '#5A5A5A',
      number: '#447788',
      bigint: '#448B88',
      specialNumber: '#3A6DA6',
      string: '#555555',
      symbol: '#558899',
      function: '#5599AA',
      object: '#2A2A2A',
      array: '#656565',
      map: '#55AAAA',
      set: '#666666',
      weakmap: '#66BBBB',
      weakset: '#444444',
      date: '#66AAAA',
      regexp: '#505050',
      error: '#5599AA',
      circularReference: '#3A3A3A',
      propertyKey: '#2A2A2A',
      punctuation: '#4A4A4A',
      indentGuide: '#A5A5A5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#C5C5C5',
      undefined: '#D5D5D5',
      boolean: '#E5E5E5',
      number: '#99EEFF',
      bigint: '#99FFFF',
      specialNumber: '#8FE4FF',
      string: '#CACACA',
      symbol: '#AAFFFF',
      function: '#88DDFF',
      object: '#B5B5B5',
      array: '#DFDFDF',
      map: '#CCFFFF',
      set: '#E0E0E0',
      weakmap: '#DDFFFF',
      weakset: '#CCCCCC',
      date: '#BBFFFF',
      regexp: '#D0D0D0',
      error: '#88EEFF',
      circularReference: '#C5C5C5',
      propertyKey: '#EEEEEE',
      punctuation: '#D5D5D5',
      indentGuide: '#6B6B6B'
    }
  } as const satisfies { light: ColorPalette; dark: ColorPalette },

  charcoalsAndMagentas: {
    light: {
      text: '#000000',
      null: '#3A3A3A',
      undefined: '#4A4A4A',
      boolean: '#5A5A5A',
      number: '#884477',
      bigint: '#885877',
      specialNumber: '#A63A6D',
      string: '#555555',
      symbol: '#995588',
      function: '#AA5599',
      object: '#2A2A2A',
      array: '#656565',
      map: '#AA66AA',
      set: '#666666',
      weakmap: '#BB77BB',
      weakset: '#444444',
      date: '#AA77AA',
      regexp: '#505050',
      error: '#BB5599',
      circularReference: '#3A3A3A',
      propertyKey: '#2A2A2A',
      punctuation: '#4A4A4A',
      indentGuide: '#A5A5A5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#C5C5C5',
      undefined: '#D5D5D5',
      boolean: '#E5E5E5',
      number: '#FFAADD',
      bigint: '#FFBEDD',
      specialNumber: '#FFA0D3',
      string: '#CACACA',
      symbol: '#FFBBEE',
      function: '#FF99DD',
      object: '#B5B5B5',
      array: '#DFDFDF',
      map: '#FFCCFF',
      set: '#E0E0E0',
      weakmap: '#FFDDFF',
      weakset: '#CCCCCC',
      date: '#FFCCEE',
      regexp: '#D0D0D0',
      error: '#FF88CC',
      circularReference: '#C5C5C5',
      propertyKey: '#EEEEEE',
      punctuation: '#D5D5D5',
      indentGuide: '#6B6B6B'
    }
  } as const satisfies { light: ColorPalette; dark: ColorPalette },

  charcoalsAndLightGrays: {
    light: {
      text: '#000000',
      null: '#3A3A3A',
      undefined: '#4A4A4A',
      boolean: '#5A5A5A',
      number: '#707070',
      bigint: '#708470',
      specialNumber: '#8E8E8E',
      string: '#555555',
      symbol: '#787878',
      function: '#808080',
      object: '#2A2A2A',
      array: '#656565',
      map: '#858585',
      set: '#666666',
      weakmap: '#909090',
      weakset: '#444444',
      date: '#888888',
      regexp: '#505050',
      error: '#7A7A7A',
      circularReference: '#3A3A3A',
      propertyKey: '#2A2A2A',
      punctuation: '#4A4A4A',
      indentGuide: '#A5A5A5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#C5C5C5',
      undefined: '#D5D5D5',
      boolean: '#E5E5E5',
      number: '#F8F8F8',
      bigint: '#F8FFF8',
      specialNumber: '#FFFFFF',
      string: '#CACACA',
      symbol: '#FDFDFD',
      function: '#FFFFFF',
      object: '#B5B5B5',
      array: '#DFDFDF',
      map: '#FAFAFA',
      set: '#E0E0E0',
      weakmap: '#FFFFFF',
      weakset: '#CCCCCC',
      date: '#F5F5F5',
      regexp: '#D0D0D0',
      error: '#F0F0F0',
      circularReference: '#C5C5C5',
      propertyKey: '#EEEEEE',
      punctuation: '#D5D5D5',
      indentGuide: '#6B6B6B'
    }
  } as const satisfies { light: ColorPalette; dark: ColorPalette }
} as const;
