/**
 * Cyans Color Range Palette Collection
 *
 * This module contains color palettes that heavily emphasize cyan colors (60-70%)
 * while incorporating complementary colors (30-40%) for variety and visual interest.
 *
 * Each palette includes both light and dark variants:
 * - Light variants use darker colors suitable for light backgrounds
 * - Dark variants use lighter colors suitable for dark backgrounds
 *
 * Available palettes:
 * - cyansAndReds: Cyan-dominant with red accents
 * - cyansAndOranges: Cyan-dominant with orange accents
 * - cyansAndYellows: Cyan-dominant with yellow accents
 * - cyansAndGreens: Cyan-dominant with green accents
 * - cyansAndBlues: Cyan-dominant with blue accents
 * - cyansAndPurples: Cyan-dominant with purple accents
 * - cyansAndBrowns: Cyan-dominant with brown accents
 * - cyansAndGreys: Cyan-dominant with grey accents
 * - cyansAndCharcoals: Cyan-dominant with charcoal accents
 * - cyansAndMagentas: Cyan-dominant with magenta accents
 * - cyansAndLightGrays: Cyan-dominant with light gray accents
 */

export const cyansColorRangePalettes = {
  cyansAndReds: {
    light: {
      text: '#000000',
      null: '#1A4A5A',
      undefined: '#2A5A6A',
      boolean: '#0A5A7A',
      number: '#7A2A2A',
      bigint: '#7A3E2A',
      specialNumber: '#982020',
      string: '#1A6A8A',
      symbol: '#2A5A8A',
      function: '#8A3A3A',
      object: '#1A5A7A',
      array: '#0A4A6A',
      map: '#2A6A9A',
      set: '#1A6AAA',
      weakmap: '#9A4A4A',
      weakset: '#3A5A7A',
      date: '#2A7AAA',
      regexp: '#1A5A8A',
      error: '#AA5A5A',
      circularReference: '#1A4A5A',
      propertyKey: '#0A3A4A',
      punctuation: '#2A5A6A',
      indentGuide: '#95ADB5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#88DDFF',
      undefined: '#99EEFF',
      boolean: '#66EEFF',
      number: '#FF9999',
      bigint: '#FFAD99',
      specialNumber: '#FF8F8F',
      string: '#88FFFF',
      symbol: '#99EEFF',
      function: '#FFAAAA',
      object: '#88EEFF',
      array: '#77DDFF',
      map: '#99FFFF',
      set: '#88FFFF',
      weakmap: '#FFBBBB',
      weakset: '#AAEEFF',
      date: '#AAFFFF',
      regexp: '#88EEFF',
      error: '#FFCCCC',
      circularReference: '#88DDFF',
      propertyKey: '#CCFFFF',
      punctuation: '#99EEFF',
      indentGuide: '#4D7780'
    }
  },
  cyansAndOranges: {
    light: {
      text: '#000000',
      null: '#1A4A5A',
      undefined: '#2A5A6A',
      boolean: '#0A5A7A',
      number: '#AA5A1A',
      bigint: '#AA6E1A',
      specialNumber: '#C85010',
      string: '#1A6A8A',
      symbol: '#2A5A8A',
      function: '#BB6A2A',
      object: '#1A5A7A',
      array: '#0A4A6A',
      map: '#2A6A9A',
      set: '#1A6AAA',
      weakmap: '#CC7A3A',
      weakset: '#3A5A7A',
      date: '#2A7AAA',
      regexp: '#1A5A8A',
      error: '#DD8A4A',
      circularReference: '#1A4A5A',
      propertyKey: '#0A3A4A',
      punctuation: '#2A5A6A',
      indentGuide: '#95ADB5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#88DDFF',
      undefined: '#99EEFF',
      boolean: '#66EEFF',
      number: '#FFBB66',
      bigint: '#FFCF66',
      specialNumber: '#FFB15C',
      string: '#88FFFF',
      symbol: '#99EEFF',
      function: '#FFCC77',
      object: '#88EEFF',
      array: '#77DDFF',
      map: '#99FFFF',
      set: '#88FFFF',
      weakmap: '#FFDD88',
      weakset: '#AAEEFF',
      date: '#AAFFFF',
      regexp: '#88EEFF',
      error: '#FFEE99',
      circularReference: '#88DDFF',
      propertyKey: '#CCFFFF',
      punctuation: '#99EEFF',
      indentGuide: '#4D7780'
    }
  },
  cyansAndYellows: {
    light: {
      text: '#000000',
      null: '#1A4A5A',
      undefined: '#2A5A6A',
      boolean: '#0A5A7A',
      number: '#AA9A1A',
      bigint: '#AAAE1A',
      specialNumber: '#C89010',
      string: '#1A6A8A',
      symbol: '#2A5A8A',
      function: '#BBAA2A',
      object: '#1A5A7A',
      array: '#0A4A6A',
      map: '#2A6A9A',
      set: '#1A6AAA',
      weakmap: '#CCBB3A',
      weakset: '#3A5A7A',
      date: '#2A7AAA',
      regexp: '#1A5A8A',
      error: '#DDCC4A',
      circularReference: '#1A4A5A',
      propertyKey: '#0A3A4A',
      punctuation: '#2A5A6A',
      indentGuide: '#95ADB5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#88DDFF',
      undefined: '#99EEFF',
      boolean: '#66EEFF',
      number: '#FFEE66',
      bigint: '#FFFF66',
      specialNumber: '#FFE45C',
      string: '#88FFFF',
      symbol: '#99EEFF',
      function: '#FFFF77',
      object: '#88EEFF',
      array: '#77DDFF',
      map: '#99FFFF',
      set: '#88FFFF',
      weakmap: '#FFFF88',
      weakset: '#AAEEFF',
      date: '#AAFFFF',
      regexp: '#88EEFF',
      error: '#FFFF99',
      circularReference: '#88DDFF',
      propertyKey: '#CCFFFF',
      punctuation: '#99EEFF',
      indentGuide: '#4D7780'
    }
  },
  cyansAndGreens: {
    light: {
      text: '#000000',
      null: '#1A4A5A',
      undefined: '#2A5A6A',
      boolean: '#0A5A7A',
      number: '#2A7A2A',
      bigint: '#2A8E2A',
      specialNumber: '#209820',
      string: '#1A6A8A',
      symbol: '#2A5A8A',
      function: '#3A8A3A',
      object: '#1A5A7A',
      array: '#0A4A6A',
      map: '#2A6A9A',
      set: '#1A6AAA',
      weakmap: '#4A9A4A',
      weakset: '#3A5A7A',
      date: '#2A7AAA',
      regexp: '#1A5A8A',
      error: '#5AAA5A',
      circularReference: '#1A4A5A',
      propertyKey: '#0A3A4A',
      punctuation: '#2A5A6A',
      indentGuide: '#95ADB5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#88DDFF',
      undefined: '#99EEFF',
      boolean: '#66EEFF',
      number: '#99FF99',
      bigint: '#99FF99',
      specialNumber: '#8FFF8F',
      string: '#88FFFF',
      symbol: '#99EEFF',
      function: '#AAFFAA',
      object: '#88EEFF',
      array: '#77DDFF',
      map: '#99FFFF',
      set: '#88FFFF',
      weakmap: '#BBFFBB',
      weakset: '#AAEEFF',
      date: '#AAFFFF',
      regexp: '#88EEFF',
      error: '#CCFFCC',
      circularReference: '#88DDFF',
      propertyKey: '#CCFFFF',
      punctuation: '#99EEFF',
      indentGuide: '#4D7780'
    }
  },
  cyansAndBlues: {
    light: {
      text: '#000000',
      null: '#1A4A5A',
      undefined: '#2A5A6A',
      boolean: '#0A5A7A',
      number: '#1A2A8A',
      bigint: '#1A3E8A',
      specialNumber: '#1020A8',
      string: '#1A6A8A',
      symbol: '#2A5A8A',
      function: '#2A3A9A',
      object: '#1A5A7A',
      array: '#0A4A6A',
      map: '#2A6A9A',
      set: '#1A6AAA',
      weakmap: '#3A4AAA',
      weakset: '#3A5A7A',
      date: '#2A7AAA',
      regexp: '#1A5A8A',
      error: '#4A5ABA',
      circularReference: '#1A4A5A',
      propertyKey: '#0A3A4A',
      punctuation: '#2A5A6A',
      indentGuide: '#95ADB5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#88DDFF',
      undefined: '#99EEFF',
      boolean: '#66EEFF',
      number: '#8899FF',
      bigint: '#88ADFF',
      specialNumber: '#7E8FFF',
      string: '#88FFFF',
      symbol: '#99EEFF',
      function: '#99AAFF',
      object: '#88EEFF',
      array: '#77DDFF',
      map: '#99FFFF',
      set: '#88FFFF',
      weakmap: '#AABBFF',
      weakset: '#AAEEFF',
      date: '#AAFFFF',
      regexp: '#88EEFF',
      error: '#BBCCFF',
      circularReference: '#88DDFF',
      propertyKey: '#CCFFFF',
      punctuation: '#99EEFF',
      indentGuide: '#4D7780'
    }
  },
  cyansAndPurples: {
    light: {
      text: '#000000',
      null: '#1A4A5A',
      undefined: '#2A5A6A',
      boolean: '#0A5A7A',
      number: '#6A2A8A',
      bigint: '#6A3E8A',
      specialNumber: '#6020A8',
      string: '#1A6A8A',
      symbol: '#2A5A8A',
      function: '#7A3A9A',
      object: '#1A5A7A',
      array: '#0A4A6A',
      map: '#2A6A9A',
      set: '#1A6AAA',
      weakmap: '#8A4AAA',
      weakset: '#3A5A7A',
      date: '#2A7AAA',
      regexp: '#1A5A8A',
      error: '#9A5ABA',
      circularReference: '#1A4A5A',
      propertyKey: '#0A3A4A',
      punctuation: '#2A5A6A',
      indentGuide: '#95ADB5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#88DDFF',
      undefined: '#99EEFF',
      boolean: '#66EEFF',
      number: '#DD99FF',
      bigint: '#DDADFF',
      specialNumber: '#D38FFF',
      string: '#88FFFF',
      symbol: '#99EEFF',
      function: '#EEAAFF',
      object: '#88EEFF',
      array: '#77DDFF',
      map: '#99FFFF',
      set: '#88FFFF',
      weakmap: '#FFBBFF',
      weakset: '#AAEEFF',
      date: '#AAFFFF',
      regexp: '#88EEFF',
      error: '#FFCCFF',
      circularReference: '#88DDFF',
      propertyKey: '#CCFFFF',
      punctuation: '#99EEFF',
      indentGuide: '#4D7780'
    }
  },
  cyansAndBrowns: {
    light: {
      text: '#000000',
      null: '#1A4A5A',
      undefined: '#2A5A6A',
      boolean: '#0A5A7A',
      number: '#6A4A2A',
      bigint: '#6A5E2A',
      specialNumber: '#884020',
      string: '#1A6A8A',
      symbol: '#2A5A8A',
      function: '#7A5A3A',
      object: '#1A5A7A',
      array: '#0A4A6A',
      map: '#2A6A9A',
      set: '#1A6AAA',
      weakmap: '#8A6A4A',
      weakset: '#3A5A7A',
      date: '#2A7AAA',
      regexp: '#1A5A8A',
      error: '#9A7A5A',
      circularReference: '#1A4A5A',
      propertyKey: '#0A3A4A',
      punctuation: '#2A5A6A',
      indentGuide: '#95ADB5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#88DDFF',
      undefined: '#99EEFF',
      boolean: '#66EEFF',
      number: '#DDBB99',
      bigint: '#DDCF99',
      specialNumber: '#FBB18F',
      string: '#88FFFF',
      symbol: '#99EEFF',
      function: '#EECCAA',
      object: '#88EEFF',
      array: '#77DDFF',
      map: '#99FFFF',
      set: '#88FFFF',
      weakmap: '#FFDDBB',
      weakset: '#AAEEFF',
      date: '#AAFFFF',
      regexp: '#88EEFF',
      error: '#FFEECC',
      circularReference: '#88DDFF',
      propertyKey: '#CCFFFF',
      punctuation: '#99EEFF',
      indentGuide: '#4D7780'
    }
  },
  cyansAndGreys: {
    light: {
      text: '#000000',
      null: '#1A4A5A',
      undefined: '#2A5A6A',
      boolean: '#0A5A7A',
      number: '#4A4A4A',
      bigint: '#4A5E4A',
      specialNumber: '#686868',
      string: '#1A6A8A',
      symbol: '#2A5A8A',
      function: '#5A5A5A',
      object: '#1A5A7A',
      array: '#0A4A6A',
      map: '#2A6A9A',
      set: '#1A6AAA',
      weakmap: '#6A6A6A',
      weakset: '#3A5A7A',
      date: '#2A7AAA',
      regexp: '#1A5A8A',
      error: '#7A7A7A',
      circularReference: '#1A4A5A',
      propertyKey: '#0A3A4A',
      punctuation: '#2A5A6A',
      indentGuide: '#95ADB5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#88DDFF',
      undefined: '#99EEFF',
      boolean: '#66EEFF',
      number: '#BBBBBB',
      bigint: '#BBCFBB',
      specialNumber: '#D9D9D9',
      string: '#88FFFF',
      symbol: '#99EEFF',
      function: '#CCCCCC',
      object: '#88EEFF',
      array: '#77DDFF',
      map: '#99FFFF',
      set: '#88FFFF',
      weakmap: '#DDDDDD',
      weakset: '#AAEEFF',
      date: '#AAFFFF',
      regexp: '#88EEFF',
      error: '#EEEEEE',
      circularReference: '#88DDFF',
      propertyKey: '#CCFFFF',
      punctuation: '#99EEFF',
      indentGuide: '#4D7780'
    }
  },
  cyansAndCharcoals: {
    light: {
      text: '#000000',
      null: '#1A4A5A',
      undefined: '#2A5A6A',
      boolean: '#0A5A7A',
      number: '#2A2A2A',
      bigint: '#2A3E2A',
      specialNumber: '#484848',
      string: '#1A6A8A',
      symbol: '#2A5A8A',
      function: '#3A3A3A',
      object: '#1A5A7A',
      array: '#0A4A6A',
      map: '#2A6A9A',
      set: '#1A6AAA',
      weakmap: '#4A4A4A',
      weakset: '#3A5A7A',
      date: '#2A7AAA',
      regexp: '#1A5A8A',
      error: '#5A5A5A',
      circularReference: '#1A4A5A',
      propertyKey: '#0A3A4A',
      punctuation: '#2A5A6A',
      indentGuide: '#95ADB5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#88DDFF',
      undefined: '#99EEFF',
      boolean: '#66EEFF',
      number: '#AAAAAA',
      bigint: '#AABEAA',
      specialNumber: '#C8C8C8',
      string: '#88FFFF',
      symbol: '#99EEFF',
      function: '#BBBBBB',
      object: '#88EEFF',
      array: '#77DDFF',
      map: '#99FFFF',
      set: '#88FFFF',
      weakmap: '#CCCCCC',
      weakset: '#AAEEFF',
      date: '#AAFFFF',
      regexp: '#88EEFF',
      error: '#DDDDDD',
      circularReference: '#88DDFF',
      propertyKey: '#CCFFFF',
      punctuation: '#99EEFF',
      indentGuide: '#4D7780'
    }
  },
  cyansAndMagentas: {
    light: {
      text: '#000000',
      null: '#1A4A5A',
      undefined: '#2A5A6A',
      boolean: '#0A5A7A',
      number: '#8A2A6A',
      bigint: '#8A3E6A',
      specialNumber: '#A82060',
      string: '#1A6A8A',
      symbol: '#2A5A8A',
      function: '#9A3A7A',
      object: '#1A5A7A',
      array: '#0A4A6A',
      map: '#2A6A9A',
      set: '#1A6AAA',
      weakmap: '#AA4A8A',
      weakset: '#3A5A7A',
      date: '#2A7AAA',
      regexp: '#1A5A8A',
      error: '#BA5A9A',
      circularReference: '#1A4A5A',
      propertyKey: '#0A3A4A',
      punctuation: '#2A5A6A',
      indentGuide: '#95ADB5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#88DDFF',
      undefined: '#99EEFF',
      boolean: '#66EEFF',
      number: '#FF99DD',
      bigint: '#FFADDD',
      specialNumber: '#FF8FD3',
      string: '#88FFFF',
      symbol: '#99EEFF',
      function: '#FFAAEE',
      object: '#88EEFF',
      array: '#77DDFF',
      map: '#99FFFF',
      set: '#88FFFF',
      weakmap: '#FFBBFF',
      weakset: '#AAEEFF',
      date: '#AAFFFF',
      regexp: '#88EEFF',
      error: '#FFCCFF',
      circularReference: '#88DDFF',
      propertyKey: '#CCFFFF',
      punctuation: '#99EEFF',
      indentGuide: '#4D7780'
    }
  },
  cyansAndLightGrays: {
    light: {
      text: '#000000',
      null: '#1A4A5A',
      undefined: '#2A5A6A',
      boolean: '#0A5A7A',
      number: '#8A8A8A',
      bigint: '#8A9E8A',
      specialNumber: '#A8A8A8',
      string: '#1A6A8A',
      symbol: '#2A5A8A',
      function: '#9A9A9A',
      object: '#1A5A7A',
      array: '#0A4A6A',
      map: '#2A6A9A',
      set: '#1A6AAA',
      weakmap: '#AAAAAA',
      weakset: '#3A5A7A',
      date: '#2A7AAA',
      regexp: '#1A5A8A',
      error: '#BABABA',
      circularReference: '#1A4A5A',
      propertyKey: '#0A3A4A',
      punctuation: '#2A5A6A',
      indentGuide: '#95ADB5'
    },
    dark: {
      text: '#FFFFFF',
      null: '#88DDFF',
      undefined: '#99EEFF',
      boolean: '#66EEFF',
      number: '#EEEEEE',
      bigint: '#EEFFEE',
      specialNumber: '#FFFFFF',
      string: '#88FFFF',
      symbol: '#99EEFF',
      function: '#F5F5F5',
      object: '#88EEFF',
      array: '#77DDFF',
      map: '#99FFFF',
      set: '#88FFFF',
      weakmap: '#FFFFFF',
      weakset: '#AAEEFF',
      date: '#AAFFFF',
      regexp: '#88EEFF',
      error: '#FFFFFF',
      circularReference: '#88DDFF',
      propertyKey: '#CCFFFF',
      punctuation: '#99EEFF',
      indentGuide: '#4D7780'
    }
  }
} as const;
