/**
 * Greys Color Range Palettes Collection
 *
 * This collection contains 11 color palettes that heavily feature grey tones (60-70%)
 * combined with accent colors from various color ranges (30-40%). Each palette includes
 * both light and dark variants for different background preferences.
 *
 * Palettes included:
 * - greysAndReds: Grey tones with red accents
 * - greysAndOranges: Grey tones with orange accents
 * - greysAndYellows: Grey tones with yellow accents
 * - greysAndGreens: Grey tones with green accents
 * - greysAndBlues: Grey tones with blue accents
 * - greysAndPurples: Grey tones with purple accents
 * - greysAndBrowns: Grey tones with brown accents
 * - greysAndCharcoals: Grey tones with charcoal/darker grey accents
 * - greysAndCyans: Grey tones with cyan accents
 * - greysAndMagentas: Grey tones with magenta accents
 * - greysAndLightGrays: Grey tones with lighter grey accents
 *
 * Light variants use darker colors suitable for light backgrounds.
 * Dark variants use lighter colors suitable for dark backgrounds.
 */

export const greysColorRangePalettes = {
  greysAndReds: {
    light: {
      null: '#5A5A5A',
      undefined: '#6A6A6A',
      boolean: '#4A4A4A',
      number: '#AA3333',
      string: '#555555',
      symbol: '#6A6A6A',
      function: '#BB4444',
      object: '#5A5A5A',
      array: '#4A4A4A',
      map: '#6A6A6A',
      set: '#555555',
      weakmap: '#CC5555',
      weakset: '#5A5A5A',
      date: '#AA3333',
      regexp: '#4A4A4A',
      error: '#DD4444',
      circularReference: '#6A6A6A',
      propertyKey: '#3A3A3A',
      punctuation: '#555555'
    },
    dark: {
      null: '#AAAAAA',
      undefined: '#BABABA',
      boolean: '#C5C5C5',
      number: '#FF8888',
      string: '#B5B5B5',
      symbol: '#BABABA',
      function: '#FFAAAA',
      object: '#AAAAAA',
      array: '#C5C5C5',
      map: '#BABABA',
      set: '#B5B5B5',
      weakmap: '#FFCCCC',
      weakset: '#AAAAAA',
      date: '#FF8888',
      regexp: '#C5C5C5',
      error: '#FFBBBB',
      circularReference: '#BABABA',
      propertyKey: '#D5D5D5',
      punctuation: '#B5B5B5'
    }
  },
  greysAndOranges: {
    light: {
      null: '#5A5A5A',
      undefined: '#6A6A6A',
      boolean: '#4A4A4A',
      number: '#CC6633',
      string: '#555555',
      symbol: '#6A6A6A',
      function: '#DD7744',
      object: '#5A5A5A',
      array: '#4A4A4A',
      map: '#6A6A6A',
      set: '#555555',
      weakmap: '#EE8855',
      weakset: '#5A5A5A',
      date: '#CC6633',
      regexp: '#4A4A4A',
      error: '#DD7744',
      circularReference: '#6A6A6A',
      propertyKey: '#3A3A3A',
      punctuation: '#555555'
    },
    dark: {
      null: '#AAAAAA',
      undefined: '#BABABA',
      boolean: '#C5C5C5',
      number: '#FFAA77',
      string: '#B5B5B5',
      symbol: '#BABABA',
      function: '#FFBB88',
      object: '#AAAAAA',
      array: '#C5C5C5',
      map: '#BABABA',
      set: '#B5B5B5',
      weakmap: '#FFCCAA',
      weakset: '#AAAAAA',
      date: '#FFAA77',
      regexp: '#C5C5C5',
      error: '#FFBB88',
      circularReference: '#BABABA',
      propertyKey: '#D5D5D5',
      punctuation: '#B5B5B5'
    }
  },
  greysAndYellows: {
    light: {
      null: '#5A5A5A',
      undefined: '#6A6A6A',
      boolean: '#4A4A4A',
      number: '#AA9933',
      string: '#555555',
      symbol: '#6A6A6A',
      function: '#BBAA44',
      object: '#5A5A5A',
      array: '#4A4A4A',
      map: '#6A6A6A',
      set: '#555555',
      weakmap: '#CCBB55',
      weakset: '#5A5A5A',
      date: '#AA9933',
      regexp: '#4A4A4A',
      error: '#BBAA44',
      circularReference: '#6A6A6A',
      propertyKey: '#3A3A3A',
      punctuation: '#555555'
    },
    dark: {
      null: '#AAAAAA',
      undefined: '#BABABA',
      boolean: '#C5C5C5',
      number: '#FFEE77',
      string: '#B5B5B5',
      symbol: '#BABABA',
      function: '#FFFF88',
      object: '#AAAAAA',
      array: '#C5C5C5',
      map: '#BABABA',
      set: '#B5B5B5',
      weakmap: '#FFFFAA',
      weakset: '#AAAAAA',
      date: '#FFEE77',
      regexp: '#C5C5C5',
      error: '#FFFF88',
      circularReference: '#BABABA',
      propertyKey: '#D5D5D5',
      punctuation: '#B5B5B5'
    }
  },
  greysAndGreens: {
    light: {
      null: '#5A5A5A',
      undefined: '#6A6A6A',
      boolean: '#4A4A4A',
      number: '#338833',
      string: '#555555',
      symbol: '#6A6A6A',
      function: '#449944',
      object: '#5A5A5A',
      array: '#4A4A4A',
      map: '#6A6A6A',
      set: '#555555',
      weakmap: '#55AA55',
      weakset: '#5A5A5A',
      date: '#338833',
      regexp: '#4A4A4A',
      error: '#449944',
      circularReference: '#6A6A6A',
      propertyKey: '#3A3A3A',
      punctuation: '#555555'
    },
    dark: {
      null: '#AAAAAA',
      undefined: '#BABABA',
      boolean: '#C5C5C5',
      number: '#88EE88',
      string: '#B5B5B5',
      symbol: '#BABABA',
      function: '#99FF99',
      object: '#AAAAAA',
      array: '#C5C5C5',
      map: '#BABABA',
      set: '#B5B5B5',
      weakmap: '#AAFFAA',
      weakset: '#AAAAAA',
      date: '#88EE88',
      regexp: '#C5C5C5',
      error: '#99FF99',
      circularReference: '#BABABA',
      propertyKey: '#D5D5D5',
      punctuation: '#B5B5B5'
    }
  },
  greysAndBlues: {
    light: {
      null: '#5A5A5A',
      undefined: '#6A6A6A',
      boolean: '#4A4A4A',
      number: '#3366AA',
      string: '#555555',
      symbol: '#6A6A6A',
      function: '#4477BB',
      object: '#5A5A5A',
      array: '#4A4A4A',
      map: '#6A6A6A',
      set: '#555555',
      weakmap: '#5588CC',
      weakset: '#5A5A5A',
      date: '#3366AA',
      regexp: '#4A4A4A',
      error: '#4477BB',
      circularReference: '#6A6A6A',
      propertyKey: '#3A3A3A',
      punctuation: '#555555'
    },
    dark: {
      null: '#AAAAAA',
      undefined: '#BABABA',
      boolean: '#C5C5C5',
      number: '#88AAFF',
      string: '#B5B5B5',
      symbol: '#BABABA',
      function: '#99BBFF',
      object: '#AAAAAA',
      array: '#C5C5C5',
      map: '#BABABA',
      set: '#B5B5B5',
      weakmap: '#AACCFF',
      weakset: '#AAAAAA',
      date: '#88AAFF',
      regexp: '#C5C5C5',
      error: '#99BBFF',
      circularReference: '#BABABA',
      propertyKey: '#D5D5D5',
      punctuation: '#B5B5B5'
    }
  },
  greysAndPurples: {
    light: {
      null: '#5A5A5A',
      undefined: '#6A6A6A',
      boolean: '#4A4A4A',
      number: '#7733AA',
      string: '#555555',
      symbol: '#6A6A6A',
      function: '#8844BB',
      object: '#5A5A5A',
      array: '#4A4A4A',
      map: '#6A6A6A',
      set: '#555555',
      weakmap: '#9955CC',
      weakset: '#5A5A5A',
      date: '#7733AA',
      regexp: '#4A4A4A',
      error: '#8844BB',
      circularReference: '#6A6A6A',
      propertyKey: '#3A3A3A',
      punctuation: '#555555'
    },
    dark: {
      null: '#AAAAAA',
      undefined: '#BABABA',
      boolean: '#C5C5C5',
      number: '#CC88FF',
      string: '#B5B5B5',
      symbol: '#BABABA',
      function: '#DD99FF',
      object: '#AAAAAA',
      array: '#C5C5C5',
      map: '#BABABA',
      set: '#B5B5B5',
      weakmap: '#EEAAFF',
      weakset: '#AAAAAA',
      date: '#CC88FF',
      regexp: '#C5C5C5',
      error: '#DD99FF',
      circularReference: '#BABABA',
      propertyKey: '#D5D5D5',
      punctuation: '#B5B5B5'
    }
  },
  greysAndBrowns: {
    light: {
      null: '#5A5A5A',
      undefined: '#6A6A6A',
      boolean: '#4A4A4A',
      number: '#885533',
      string: '#555555',
      symbol: '#6A6A6A',
      function: '#996644',
      object: '#5A5A5A',
      array: '#4A4A4A',
      map: '#6A6A6A',
      set: '#555555',
      weakmap: '#AA7755',
      weakset: '#5A5A5A',
      date: '#885533',
      regexp: '#4A4A4A',
      error: '#996644',
      circularReference: '#6A6A6A',
      propertyKey: '#3A3A3A',
      punctuation: '#555555'
    },
    dark: {
      null: '#AAAAAA',
      undefined: '#BABABA',
      boolean: '#C5C5C5',
      number: '#DDAA88',
      string: '#B5B5B5',
      symbol: '#BABABA',
      function: '#EEBB99',
      object: '#AAAAAA',
      array: '#C5C5C5',
      map: '#BABABA',
      set: '#B5B5B5',
      weakmap: '#FFCCAA',
      weakset: '#AAAAAA',
      date: '#DDAA88',
      regexp: '#C5C5C5',
      error: '#EEBB99',
      circularReference: '#BABABA',
      propertyKey: '#D5D5D5',
      punctuation: '#B5B5B5'
    }
  },
  greysAndCharcoals: {
    light: {
      null: '#5A5A5A',
      undefined: '#6A6A6A',
      boolean: '#4A4A4A',
      number: '#2A2A2A',
      string: '#555555',
      symbol: '#6A6A6A',
      function: '#3A3A3A',
      object: '#5A5A5A',
      array: '#4A4A4A',
      map: '#6A6A6A',
      set: '#555555',
      weakmap: '#1A1A1A',
      weakset: '#5A5A5A',
      date: '#2A2A2A',
      regexp: '#4A4A4A',
      error: '#3A3A3A',
      circularReference: '#6A6A6A',
      propertyKey: '#3A3A3A',
      punctuation: '#555555'
    },
    dark: {
      null: '#AAAAAA',
      undefined: '#BABABA',
      boolean: '#C5C5C5',
      number: '#888888',
      string: '#B5B5B5',
      symbol: '#BABABA',
      function: '#999999',
      object: '#AAAAAA',
      array: '#C5C5C5',
      map: '#BABABA',
      set: '#B5B5B5',
      weakmap: '#777777',
      weakset: '#AAAAAA',
      date: '#888888',
      regexp: '#C5C5C5',
      error: '#999999',
      circularReference: '#BABABA',
      propertyKey: '#D5D5D5',
      punctuation: '#B5B5B5'
    }
  },
  greysAndCyans: {
    light: {
      null: '#5A5A5A',
      undefined: '#6A6A6A',
      boolean: '#4A4A4A',
      number: '#3388AA',
      string: '#555555',
      symbol: '#6A6A6A',
      function: '#4499BB',
      object: '#5A5A5A',
      array: '#4A4A4A',
      map: '#6A6A6A',
      set: '#555555',
      weakmap: '#55AACC',
      weakset: '#5A5A5A',
      date: '#3388AA',
      regexp: '#4A4A4A',
      error: '#4499BB',
      circularReference: '#6A6A6A',
      propertyKey: '#3A3A3A',
      punctuation: '#555555'
    },
    dark: {
      null: '#AAAAAA',
      undefined: '#BABABA',
      boolean: '#C5C5C5',
      number: '#88EEFF',
      string: '#B5B5B5',
      symbol: '#BABABA',
      function: '#99FFFF',
      object: '#AAAAAA',
      array: '#C5C5C5',
      map: '#BABABA',
      set: '#B5B5B5',
      weakmap: '#AAFFFF',
      weakset: '#AAAAAA',
      date: '#88EEFF',
      regexp: '#C5C5C5',
      error: '#99FFFF',
      circularReference: '#BABABA',
      propertyKey: '#D5D5D5',
      punctuation: '#B5B5B5'
    }
  },
  greysAndMagentas: {
    light: {
      null: '#5A5A5A',
      undefined: '#6A6A6A',
      boolean: '#4A4A4A',
      number: '#AA3388',
      string: '#555555',
      symbol: '#6A6A6A',
      function: '#BB4499',
      object: '#5A5A5A',
      array: '#4A4A4A',
      map: '#6A6A6A',
      set: '#555555',
      weakmap: '#CC55AA',
      weakset: '#5A5A5A',
      date: '#AA3388',
      regexp: '#4A4A4A',
      error: '#BB4499',
      circularReference: '#6A6A6A',
      propertyKey: '#3A3A3A',
      punctuation: '#555555'
    },
    dark: {
      null: '#AAAAAA',
      undefined: '#BABABA',
      boolean: '#C5C5C5',
      number: '#FF88EE',
      string: '#B5B5B5',
      symbol: '#BABABA',
      function: '#FF99FF',
      object: '#AAAAAA',
      array: '#C5C5C5',
      map: '#BABABA',
      set: '#B5B5B5',
      weakmap: '#FFAAFF',
      weakset: '#AAAAAA',
      date: '#FF88EE',
      regexp: '#C5C5C5',
      error: '#FF99FF',
      circularReference: '#BABABA',
      propertyKey: '#D5D5D5',
      punctuation: '#B5B5B5'
    }
  },
  greysAndLightGrays: {
    light: {
      null: '#5A5A5A',
      undefined: '#6A6A6A',
      boolean: '#4A4A4A',
      number: '#8A8A8A',
      string: '#555555',
      symbol: '#6A6A6A',
      function: '#9A9A9A',
      object: '#5A5A5A',
      array: '#4A4A4A',
      map: '#6A6A6A',
      set: '#555555',
      weakmap: '#AAAAAA',
      weakset: '#5A5A5A',
      date: '#8A8A8A',
      regexp: '#4A4A4A',
      error: '#9A9A9A',
      circularReference: '#6A6A6A',
      propertyKey: '#3A3A3A',
      punctuation: '#555555'
    },
    dark: {
      null: '#AAAAAA',
      undefined: '#BABABA',
      boolean: '#C5C5C5',
      number: '#EEEEEE',
      string: '#B5B5B5',
      symbol: '#BABABA',
      function: '#F5F5F5',
      object: '#AAAAAA',
      array: '#C5C5C5',
      map: '#BABABA',
      set: '#B5B5B5',
      weakmap: '#FFFFFF',
      weakset: '#AAAAAA',
      date: '#EEEEEE',
      regexp: '#C5C5C5',
      error: '#F5F5F5',
      circularReference: '#BABABA',
      propertyKey: '#D5D5D5',
      punctuation: '#B5B5B5'
    }
  }
} as const;
