/**
 * Light Grays Color Range Palettes Collection
 *
 * This collection contains 11 color palettes that heavily feature light gray tones (60-70%)
 * combined with accent colors from various color ranges (30-40%). Each palette includes
 * both light and dark variants for different background preferences.
 *
 * Palettes included:
 * - lightGraysAndReds: Light gray tones with red accents
 * - lightGraysAndOranges: Light gray tones with orange accents
 * - lightGraysAndYellows: Light gray tones with yellow accents
 * - lightGraysAndGreens: Light gray tones with green accents
 * - lightGraysAndBlues: Light gray tones with blue accents
 * - lightGraysAndPurples: Light gray tones with purple accents
 * - lightGraysAndBrowns: Light gray tones with brown accents
 * - lightGraysAndGreys: Light gray tones with medium grey accents
 * - lightGraysAndCharcoals: Light gray tones with charcoal/darker accents
 * - lightGraysAndCyans: Light gray tones with cyan accents
 * - lightGraysAndMagentas: Light gray tones with magenta accents
 *
 * Light variants use darker colors suitable for light backgrounds.
 * Dark variants use lighter colors suitable for dark backgrounds.
 */

export const lightGraysColorRangePalettes = {
  lightGraysAndReds: {
    light: {
      text: '#000000',
      null: '#8A8A8A',
      undefined: '#9A9A9A',
      boolean: '#7A7A7A',
      number: '#AA3333',
      bigint: '#AA4733',
      specialNumber: '#C82929',
      string: '#858585',
      symbol: '#9A9A9A',
      function: '#BB4444',
      object: '#8A8A8A',
      array: '#7A7A7A',
      map: '#9A9A9A',
      set: '#858585',
      weakmap: '#CC5555',
      weakset: '#8A8A8A',
      date: '#AA3333',
      regexp: '#7A7A7A',
      error: '#DD4444',
      circularReference: '#9A9A9A',
      propertyKey: '#6A6A6A',
      punctuation: '#858585',
      indentGuide: '#C2C2C2'
    },
    dark: {
      text: '#FFFFFF',
      null: '#DADADA',
      undefined: '#EAEAEA',
      boolean: '#F5F5F5',
      number: '#FF8888',
      bigint: '#FF9C88',
      specialNumber: '#FF7E7E',
      string: '#E5E5E5',
      symbol: '#EAEAEA',
      function: '#FFAAAA',
      object: '#DADADA',
      array: '#F5F5F5',
      map: '#EAEAEA',
      set: '#E5E5E5',
      weakmap: '#FFCCCC',
      weakset: '#DADADA',
      date: '#FF8888',
      regexp: '#F5F5F5',
      error: '#FFBBBB',
      circularReference: '#EAEAEA',
      propertyKey: '#FFFFFF',
      punctuation: '#E5E5E5',
      indentGuide: '#737373'
    }
  },
  lightGraysAndOranges: {
    light: {
      text: '#000000',
      null: '#8A8A8A',
      undefined: '#9A9A9A',
      boolean: '#7A7A7A',
      number: '#CC6633',
      bigint: '#CC7A33',
      specialNumber: '#EA5C29',
      string: '#858585',
      symbol: '#9A9A9A',
      function: '#DD7744',
      object: '#8A8A8A',
      array: '#7A7A7A',
      map: '#9A9A9A',
      set: '#858585',
      weakmap: '#EE8855',
      weakset: '#8A8A8A',
      date: '#CC6633',
      regexp: '#7A7A7A',
      error: '#DD7744',
      circularReference: '#9A9A9A',
      propertyKey: '#6A6A6A',
      punctuation: '#858585',
      indentGuide: '#C2C2C2'
    },
    dark: {
      text: '#FFFFFF',
      null: '#DADADA',
      undefined: '#EAEAEA',
      boolean: '#F5F5F5',
      number: '#FFAA77',
      bigint: '#FFBE77',
      specialNumber: '#FFA06D',
      string: '#E5E5E5',
      symbol: '#EAEAEA',
      function: '#FFBB88',
      object: '#DADADA',
      array: '#F5F5F5',
      map: '#EAEAEA',
      set: '#E5E5E5',
      weakmap: '#FFCCAA',
      weakset: '#DADADA',
      date: '#FFAA77',
      regexp: '#F5F5F5',
      error: '#FFBB88',
      circularReference: '#EAEAEA',
      propertyKey: '#FFFFFF',
      punctuation: '#E5E5E5',
      indentGuide: '#737373'
    }
  },
  lightGraysAndYellows: {
    light: {
      text: '#000000',
      null: '#8A8A8A',
      undefined: '#9A9A9A',
      boolean: '#7A7A7A',
      number: '#AA9933',
      bigint: '#AAAD33',
      specialNumber: '#C88F29',
      string: '#858585',
      symbol: '#9A9A9A',
      function: '#BBAA44',
      object: '#8A8A8A',
      array: '#7A7A7A',
      map: '#9A9A9A',
      set: '#858585',
      weakmap: '#CCBB55',
      weakset: '#8A8A8A',
      date: '#AA9933',
      regexp: '#7A7A7A',
      error: '#BBAA44',
      circularReference: '#9A9A9A',
      propertyKey: '#6A6A6A',
      punctuation: '#858585',
      indentGuide: '#C2C2C2'
    },
    dark: {
      text: '#FFFFFF',
      null: '#DADADA',
      undefined: '#EAEAEA',
      boolean: '#F5F5F5',
      number: '#FFEE77',
      bigint: '#FFFF77',
      specialNumber: '#FFE46D',
      string: '#E5E5E5',
      symbol: '#EAEAEA',
      function: '#FFFF88',
      object: '#DADADA',
      array: '#F5F5F5',
      map: '#EAEAEA',
      set: '#E5E5E5',
      weakmap: '#FFFFAA',
      weakset: '#DADADA',
      date: '#FFEE77',
      regexp: '#F5F5F5',
      error: '#FFFF88',
      circularReference: '#EAEAEA',
      propertyKey: '#FFFFFF',
      punctuation: '#E5E5E5',
      indentGuide: '#737373'
    }
  },
  lightGraysAndGreens: {
    light: {
      text: '#000000',
      null: '#8A8A8A',
      undefined: '#9A9A9A',
      boolean: '#7A7A7A',
      number: '#338833',
      bigint: '#339C33',
      specialNumber: '#29A629',
      string: '#858585',
      symbol: '#9A9A9A',
      function: '#449944',
      object: '#8A8A8A',
      array: '#7A7A7A',
      map: '#9A9A9A',
      set: '#858585',
      weakmap: '#55AA55',
      weakset: '#8A8A8A',
      date: '#338833',
      regexp: '#7A7A7A',
      error: '#449944',
      circularReference: '#9A9A9A',
      propertyKey: '#6A6A6A',
      punctuation: '#858585',
      indentGuide: '#C2C2C2'
    },
    dark: {
      text: '#FFFFFF',
      null: '#DADADA',
      undefined: '#EAEAEA',
      boolean: '#F5F5F5',
      number: '#88EE88',
      bigint: '#88FF88',
      specialNumber: '#7EFF7E',
      string: '#E5E5E5',
      symbol: '#EAEAEA',
      function: '#99FF99',
      object: '#DADADA',
      array: '#F5F5F5',
      map: '#EAEAEA',
      set: '#E5E5E5',
      weakmap: '#AAFFAA',
      weakset: '#DADADA',
      date: '#88EE88',
      regexp: '#F5F5F5',
      error: '#99FF99',
      circularReference: '#EAEAEA',
      propertyKey: '#FFFFFF',
      punctuation: '#E5E5E5',
      indentGuide: '#737373'
    }
  },
  lightGraysAndBlues: {
    light: {
      text: '#000000',
      null: '#8A8A8A',
      undefined: '#9A9A9A',
      boolean: '#7A7A7A',
      number: '#3366AA',
      bigint: '#337AAA',
      specialNumber: '#295CC8',
      string: '#858585',
      symbol: '#9A9A9A',
      function: '#4477BB',
      object: '#8A8A8A',
      array: '#7A7A7A',
      map: '#9A9A9A',
      set: '#858585',
      weakmap: '#5588CC',
      weakset: '#8A8A8A',
      date: '#3366AA',
      regexp: '#7A7A7A',
      error: '#4477BB',
      circularReference: '#9A9A9A',
      propertyKey: '#6A6A6A',
      punctuation: '#858585',
      indentGuide: '#C2C2C2'
    },
    dark: {
      text: '#FFFFFF',
      null: '#DADADA',
      undefined: '#EAEAEA',
      boolean: '#F5F5F5',
      number: '#88AAFF',
      bigint: '#88BEFF',
      specialNumber: '#7EA0FF',
      string: '#E5E5E5',
      symbol: '#EAEAEA',
      function: '#99BBFF',
      object: '#DADADA',
      array: '#F5F5F5',
      map: '#EAEAEA',
      set: '#E5E5E5',
      weakmap: '#AACCFF',
      weakset: '#DADADA',
      date: '#88AAFF',
      regexp: '#F5F5F5',
      error: '#99BBFF',
      circularReference: '#EAEAEA',
      propertyKey: '#FFFFFF',
      punctuation: '#E5E5E5',
      indentGuide: '#737373'
    }
  },
  lightGraysAndPurples: {
    light: {
      text: '#000000',
      null: '#8A8A8A',
      undefined: '#9A9A9A',
      boolean: '#7A7A7A',
      number: '#7733AA',
      bigint: '#7747AA',
      specialNumber: '#6D29C8',
      string: '#858585',
      symbol: '#9A9A9A',
      function: '#8844BB',
      object: '#8A8A8A',
      array: '#7A7A7A',
      map: '#9A9A9A',
      set: '#858585',
      weakmap: '#9955CC',
      weakset: '#8A8A8A',
      date: '#7733AA',
      regexp: '#7A7A7A',
      error: '#8844BB',
      circularReference: '#9A9A9A',
      propertyKey: '#6A6A6A',
      punctuation: '#858585',
      indentGuide: '#C2C2C2'
    },
    dark: {
      text: '#FFFFFF',
      null: '#DADADA',
      undefined: '#EAEAEA',
      boolean: '#F5F5F5',
      number: '#CC88FF',
      bigint: '#CC9CFF',
      specialNumber: '#C27EFF',
      string: '#E5E5E5',
      symbol: '#EAEAEA',
      function: '#DD99FF',
      object: '#DADADA',
      array: '#F5F5F5',
      map: '#EAEAEA',
      set: '#E5E5E5',
      weakmap: '#EEAAFF',
      weakset: '#DADADA',
      date: '#CC88FF',
      regexp: '#F5F5F5',
      error: '#DD99FF',
      circularReference: '#EAEAEA',
      propertyKey: '#FFFFFF',
      punctuation: '#E5E5E5',
      indentGuide: '#737373'
    }
  },
  lightGraysAndBrowns: {
    light: {
      text: '#000000',
      null: '#8A8A8A',
      undefined: '#9A9A9A',
      boolean: '#7A7A7A',
      number: '#885533',
      bigint: '#886933',
      specialNumber: '#A64B29',
      string: '#858585',
      symbol: '#9A9A9A',
      function: '#996644',
      object: '#8A8A8A',
      array: '#7A7A7A',
      map: '#9A9A9A',
      set: '#858585',
      weakmap: '#AA7755',
      weakset: '#8A8A8A',
      date: '#885533',
      regexp: '#7A7A7A',
      error: '#996644',
      circularReference: '#9A9A9A',
      propertyKey: '#6A6A6A',
      punctuation: '#858585',
      indentGuide: '#C2C2C2'
    },
    dark: {
      text: '#FFFFFF',
      null: '#DADADA',
      undefined: '#EAEAEA',
      boolean: '#F5F5F5',
      number: '#DDAA88',
      bigint: '#DDBE88',
      specialNumber: '#FBA07E',
      string: '#E5E5E5',
      symbol: '#EAEAEA',
      function: '#EEBB99',
      object: '#DADADA',
      array: '#F5F5F5',
      map: '#EAEAEA',
      set: '#E5E5E5',
      weakmap: '#FFCCAA',
      weakset: '#DADADA',
      date: '#DDAA88',
      regexp: '#F5F5F5',
      error: '#EEBB99',
      circularReference: '#EAEAEA',
      propertyKey: '#FFFFFF',
      punctuation: '#E5E5E5',
      indentGuide: '#737373'
    }
  },
  lightGraysAndGreys: {
    light: {
      text: '#000000',
      null: '#8A8A8A',
      undefined: '#9A9A9A',
      boolean: '#7A7A7A',
      number: '#5A5A5A',
      bigint: '#5A6E5A',
      specialNumber: '#787878',
      string: '#858585',
      symbol: '#9A9A9A',
      function: '#6A6A6A',
      object: '#8A8A8A',
      array: '#7A7A7A',
      map: '#9A9A9A',
      set: '#858585',
      weakmap: '#4A4A4A',
      weakset: '#8A8A8A',
      date: '#5A5A5A',
      regexp: '#7A7A7A',
      error: '#6A6A6A',
      circularReference: '#9A9A9A',
      propertyKey: '#6A6A6A',
      punctuation: '#858585',
      indentGuide: '#C2C2C2'
    },
    dark: {
      text: '#FFFFFF',
      null: '#DADADA',
      undefined: '#EAEAEA',
      boolean: '#F5F5F5',
      number: '#AAAAAA',
      bigint: '#AABEAA',
      specialNumber: '#C8C8C8',
      string: '#E5E5E5',
      symbol: '#EAEAEA',
      function: '#BABABA',
      object: '#DADADA',
      array: '#F5F5F5',
      map: '#EAEAEA',
      set: '#E5E5E5',
      weakmap: '#999999',
      weakset: '#DADADA',
      date: '#AAAAAA',
      regexp: '#F5F5F5',
      error: '#BABABA',
      circularReference: '#EAEAEA',
      propertyKey: '#FFFFFF',
      punctuation: '#E5E5E5',
      indentGuide: '#737373'
    }
  },
  lightGraysAndCharcoals: {
    light: {
      text: '#000000',
      null: '#8A8A8A',
      undefined: '#9A9A9A',
      boolean: '#7A7A7A',
      number: '#2A2A2A',
      bigint: '#2A3E2A',
      specialNumber: '#484848',
      string: '#858585',
      symbol: '#9A9A9A',
      function: '#3A3A3A',
      object: '#8A8A8A',
      array: '#7A7A7A',
      map: '#9A9A9A',
      set: '#858585',
      weakmap: '#1A1A1A',
      weakset: '#8A8A8A',
      date: '#2A2A2A',
      regexp: '#7A7A7A',
      error: '#3A3A3A',
      circularReference: '#9A9A9A',
      propertyKey: '#6A6A6A',
      punctuation: '#858585',
      indentGuide: '#C2C2C2'
    },
    dark: {
      text: '#FFFFFF',
      null: '#DADADA',
      undefined: '#EAEAEA',
      boolean: '#F5F5F5',
      number: '#888888',
      bigint: '#889C88',
      specialNumber: '#A6A6A6',
      string: '#E5E5E5',
      symbol: '#EAEAEA',
      function: '#999999',
      object: '#DADADA',
      array: '#F5F5F5',
      map: '#EAEAEA',
      set: '#E5E5E5',
      weakmap: '#777777',
      weakset: '#DADADA',
      date: '#888888',
      regexp: '#F5F5F5',
      error: '#999999',
      circularReference: '#EAEAEA',
      propertyKey: '#FFFFFF',
      punctuation: '#E5E5E5',
      indentGuide: '#737373'
    }
  },
  lightGraysAndCyans: {
    light: {
      text: '#000000',
      null: '#8A8A8A',
      undefined: '#9A9A9A',
      boolean: '#7A7A7A',
      number: '#3388AA',
      bigint: '#339CAA',
      specialNumber: '#297EC8',
      string: '#858585',
      symbol: '#9A9A9A',
      function: '#4499BB',
      object: '#8A8A8A',
      array: '#7A7A7A',
      map: '#9A9A9A',
      set: '#858585',
      weakmap: '#55AACC',
      weakset: '#8A8A8A',
      date: '#3388AA',
      regexp: '#7A7A7A',
      error: '#4499BB',
      circularReference: '#9A9A9A',
      propertyKey: '#6A6A6A',
      punctuation: '#858585',
      indentGuide: '#C2C2C2'
    },
    dark: {
      text: '#FFFFFF',
      null: '#DADADA',
      undefined: '#EAEAEA',
      boolean: '#F5F5F5',
      number: '#88EEFF',
      bigint: '#88FFFF',
      specialNumber: '#7EE4FF',
      string: '#E5E5E5',
      symbol: '#EAEAEA',
      function: '#99FFFF',
      object: '#DADADA',
      array: '#F5F5F5',
      map: '#EAEAEA',
      set: '#E5E5E5',
      weakmap: '#AAFFFF',
      weakset: '#DADADA',
      date: '#88EEFF',
      regexp: '#F5F5F5',
      error: '#99FFFF',
      circularReference: '#EAEAEA',
      propertyKey: '#FFFFFF',
      punctuation: '#E5E5E5',
      indentGuide: '#737373'
    }
  },
  lightGraysAndMagentas: {
    light: {
      text: '#000000',
      null: '#8A8A8A',
      undefined: '#9A9A9A',
      boolean: '#7A7A7A',
      number: '#AA3388',
      bigint: '#AA4788',
      specialNumber: '#C8297E',
      string: '#858585',
      symbol: '#9A9A9A',
      function: '#BB4499',
      object: '#8A8A8A',
      array: '#7A7A7A',
      map: '#9A9A9A',
      set: '#858585',
      weakmap: '#CC55AA',
      weakset: '#8A8A8A',
      date: '#AA3388',
      regexp: '#7A7A7A',
      error: '#BB4499',
      circularReference: '#9A9A9A',
      propertyKey: '#6A6A6A',
      punctuation: '#858585',
      indentGuide: '#C2C2C2'
    },
    dark: {
      text: '#FFFFFF',
      null: '#DADADA',
      undefined: '#EAEAEA',
      boolean: '#F5F5F5',
      number: '#FF88EE',
      bigint: '#FF9CEE',
      specialNumber: '#FF7EE4',
      string: '#E5E5E5',
      symbol: '#EAEAEA',
      function: '#FF99FF',
      object: '#DADADA',
      array: '#F5F5F5',
      map: '#EAEAEA',
      set: '#E5E5E5',
      weakmap: '#FFAAFF',
      weakset: '#DADADA',
      date: '#FF88EE',
      regexp: '#F5F5F5',
      error: '#FF99FF',
      circularReference: '#EAEAEA',
      propertyKey: '#FFFFFF',
      punctuation: '#E5E5E5',
      indentGuide: '#737373'
    }
  }
} as const;
